name: Deploy app to AWS
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
  
jobs:
  deployment:
    runs-on: ubuntu-latest
    
    steps:
      
      - uses: actions/checkout@v2
      
      - name: node.js enviroment
        uses: actions/setup-node@v2
        
      - name: npm install & build
        run: |
          npm install
          npm run build
      
      - name: S3 deploy aws
        uses: sai-sharan/aws-s3-sync-action@v0.1.0
        with:
          access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: 'eu-central-1'
          source: 'www'
          destination_bucket: ${{ secrets.AWS_S3_BUCKET }}
          delete: true
          quiet: false
        
          
